export const categoriaIconos: Record<string, string> = {
  Todos: "🌐",

  Inmuebles: "🏠",
  Propiedades: "🏠",
  Casas: "🏡",
  Departamentos: "🏢",
  Dúplex: "🏘️",
  Terrenos: "🗺️",
  Lotes: "📍",
  Monoambientes: "🏙️",
  Habitaciones: "🛏️",
  Salones: "🏬",
  "Locales comerciales": "🏪",
  Oficinas: "🏢",
  Depósitos: "📦",
  Tinglados: "🏗️",
  Quintas: "🌳",
  Campos: "🌾",
  Garajes: "🚗",
  Alquileres: "🔑",
  "Propiedades en pozo": "🏗️",
  "Inversiones inmobiliarias": "📈",

  "Vehículos/Motos": "🚗",
  "Repuestos y Accesorios": "🧰",
  Electrodomésticos: "💡",
  "Electrónica y Accesorios": "📱",
  "Informática y Celulares": "💻",
  "Muebles y Hogar": "🛋️",
  "Ropa y Calzados": "👟",
  "Moda y Accesorios": "👜",
  "Bebés y Niños": "🧸",
  Mascotas: "🐶",

  Supermercado: "🏪",
  "Despensa / Bodega": "🛒",
  "Comidas y Bebidas": "🍔",
  Panadería: "🥖",
  Rotisería: "🍱",
  Heladería: "🍨",

  "Delivery / Mensajería": "🛵",
  Farmacia: "💊",
  Ferretería: "🛠️",
  Herramientas: "🔧",
  Construcción: "🧱",
  Educación: "📚",

  Servicios: "🤝",
  "Servicios profesionales": "💼",
  Plomería: "🚿",
  Electricidad: "💡",
  Albañilería: "🧱",
  Jardinería: "🌿",
  Limpieza: "🧹",
  Reparaciones: "🔩",
  "Belleza y Barbería": "💈",
  Peluquería: "💇‍♂️",
  Eventos: "🎉",
  "Fotografía y Video": "📸",
  "Clases particulares": "🧑‍🏫",
  "Transporte y Fletes": "🚚",
  "Taller Mecánico": "🔧",

  Lavadero: "🧼",
  Deportes: "⚽",
  "Salud y Bienestar": "🩺",
  "Agro y Campo": "🌱",
  Vivero: "🌱",
  Maquinarias: "🚜",
  "Librería y Oficina": "✏️",
  Emprendedores: "🚀",
  Artesanías: "🎨",
};

export const obtenerIconoCategoria = (nombre: string): string => {
  return categoriaIconos[nombre] || "📦";
};
